// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dntyiiqijkjxvlhqfehv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRudHlpaXFpamtqeHZsaHFmZWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NTI1NjgsImV4cCI6MjA1ODAyODU2OH0.2_cUgzSfPAEps1vlIWiVG6PTq74jSS0H148qph3akbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);